### ISSUE TITLE
Öneri.

### ISSUE THREAD

**Issue by mertushka** [ikramimamoglu/hax-api#1]
Merhaba Yağız, bu projeyi hala geliştirmeyi düşünüyorsun sana bir önerim var. Sadece bu proje için değil diğer projelerin içinde kullanabilirsin. İşini fazlasıyla kolaylaştıracağını düşünüyorum. Herhangi bir sorun olursa benimle iletişime geçebilirsin.

NPM
https://www.npmjs.com/package/haxball.js

Github
https://github.com/mertushka/haxball.js

**Comment by ikramimamoglu** [comment]
Kaynak kodu incelemeye vakit buldugum zaman deneyecegim. Tesekkurler.
